### ISSUE TITLE
HUD doesn't show the selected weapon when picking them up

### ISSUE THREAD

**Issue by Aleoris** [WillTarte/EMU#40] opened 2020-11-07 15:23 UTC

**Comment by WillTarte** [comment] 2020-11-16 20:06
This might be getting fixed by #43

**Comment by ClaudiaLapalme** [comment] 2020-11-16 20:10
I think I saw them as selection in the weapon refinement branch

**Comment by ClaudiaLapalme** [comment] 2020-11-16 20:20
I confirm: This is not a bug. There is a little box around the primary weapon when i pick up a weapon and then i can see when i switch between both

**Closed by ClaudiaLapalme** 2020-11-16 20:20 UTC
Labels: bug
