### ISSUE TITLE
Link the PlayerController with the spritesheets

### ISSUE THREAD

**Issue by WillTarte** [WillTarte/EMU#38] opened 2020-11-07 15:15 UTC
Depends on part of #8 
Link the different player spritesheets with the player controller

**Comment by ClaudiaLapalme** [comment] 2020-11-24 02:27
This feels like a duplicate of #9. Can I close it? @WillTarte @Wmbat @Aleoris @tedgag

**Closed** 2020-12-02 21:02 UTC
Labels: Gameplay, UI
